### ISSUE TITLE
Parallelizing of Gmsh meshes not clearly documented

### ISSUE THREAD

**Issue by lancaster17** [usnistgov/fipy#609]
I created a 3D spherical mesh in Gmsh 3.0.5 and trying to import to fipy 3.1.3. The following code works when run as `python test_gmsh.py` but crashes when run with `mpirun -np 8 python test_gmsh.py`
```python
#!/usr/bin/env python2
import fipy

mesh = fipy.Gmsh3D('sphere.msh')
```
The error is:
```
Traceback (most recent call last):
  File "test_gmsh.py", line 3, in <module>
    mesh = fipy.Gmsh3D('sphere.msh')
  File "/usr/lib/python2.7/site-packages/fipy/meshes/gmshMesh.py", line 1944, in __init__
    self._orderedCellVertexIDs_data) = self.mshFile.read()
  File "/usr/lib/python2.7/site-packages/fipy/meshes/gmshMesh.py", line 809, in read
    raise GmshException(errStr)
fipy.meshes.gmshMesh.GmshException: Gmsh hasn't produced any cells! Check your Gmsh code.

Gmsh output:
```

If I replace `.msh` file with `.geo` file it works in both cases, however the mesh seems to be different from one generated in Gmsh.

**Comment by guyer** [comment]
Can you post the `.msh` and `.geo` files to [gist](http://gist.github.com) or similar?

**Comment by lancaster17** [comment]
Of course, here they are
https://gist.github.com/lancaster17/dc775bd23cf066debba455192a51c88e

I also noticed that there is no error if i invoke `mpirun` with only one process. There is also no error if i manually set the communicator to `serialComm` like this:
``` python
mesh = fipy.Gmsh3D('sphere.msh', communicator = fipy.serialComm) 
```
but if I do the code seem to be executed in serial way with low performance.

It seems as if the file object gets deleted after the root process reads it and the rest cannot find the file anymore.

**Comment by guyer** [comment]
The issue is that there's no partitioning information in your `.msh` file. There's no particular reason you'd have seen it, but the [help for the `MSHFile` object](https://github.com/usnistgov/fipy/blob/develop/fipy/meshes/gmshMesh.py#L500) says:

> Can handle a partitioned mesh based on `parallelComm.Nproc`. If partitioning,
    the msh file must either be previously partitioned with the number of
    partitions matching `Nproc`, or the mesh must be specified with a geo file
    or multiline string.

We need to more clearly document how FiPy handles partitioning (or, more accurately, how FiPy gets Gmsh to handle partitioning).

You can manually direct Gmsh to partition your mesh for you: 
> `gmsh -3 -nopopup -format msh -o sphere2.msh -part 8 sphere.msh`
or you can let FiPy handle it by passing in our `.geo` file. 

The same version of gmsh produce the same `.msh` from your `.geo`, irrespective of whether FiPy calls gmsh or you do. This is not reliably true for different versions of gmsh. If you find a case where that's not true, please let us know.

**Comment by guyer** [comment]
I've updated the title of this issue to reflect that it's a documentation problem, not a functionality problem.

**Comment by guyer** [comment]
*Now* I've updated the title
