### ISSUE TITLE
use of Variables?

### ISSUE THREAD

**Issue by oliverstefanov** [usnistgov/fipy#619]
I have doubts regarding the use of "Variable". In the phase field demos, the anisotropic diffusion coefficient is built using "variable" matrices, e.g. I0=Variable((1,0),(0,1)). I assume that a Variable is used for this constant matrix to make the diffusion coefficient a variable also, forcing to be reevaluated at each timestep ?

If I have a coefficient that depends on elapsed time and cell variables, such as in the transient term of directional solidification PF models, should elapsed time be declared as a Variable also ? I feel it would make sense but I usually get errors/warnings when I do this as fipy wants a cell variable as a coefficient

**Comment by guyer** [comment]
In [anisotropy.py](https://www.ctcms.nist.gov/fipy/examples/phase/generated/examples.phase.anisotropy.html), let's look at it working backwards. 

- `phaseEq` has a `DiffusionTerm`.
- The coefficient of a `DiffusionTerm` must be either a rank-0 scalar or a rank-1 tensor. If rank-0, it can either be a single Python float or it can be a `MeshVariable` (either `FaceVariable` or `CellVariable`). If rank-1, it should be a `MeshVariable` (it's possible you could get an appropriately nested tuple or list to work, but I wouldn't promise it).
- For this problem, with anisotropic diffusion, we want a rank-1 coefficient.
- In this case, the coefficient `D` depends on the solution variable, via \beta and so we want it to reflect both spatial and temporal variations in \phi, so we want to write a FiPy Variable expression that produces a rank-1 `FaceVariable`.
- The key to writing the expression
   ```python
   D = alpha**2 * (1.+ c * beta) * (Ddia * I0 + Doff * I1)
   ```
   is making sure that Python doesn't grab ahold of it and do arithmetic prematurely. We want a lazily evaluated expression that always reflects the current value of \phi. The way to do that to compose things in such a way that the Python interpreter asks FiPy to do the multiplications and additions.
- Because `Ddia` and `Doff` depend on `phi` (via `beta`, `Phi`, and `PhiSq`, ...), it would *probably* work if `I0` and `I1` were just written as tuples or lists, but there's a chance that Python would try (and fail) to list concatenation, especially if the order were reversed, e.g., `IO * Ddia`.
- So, we cast `I0` and `I1` to `Variable` objects to ensure that all of the interpretation is done by FiPy and not by Python.

As to how to write a time and `CellVariable` dependent coefficient to a `TransientTerm`, yes, you should probably write elapsed time as a `Variable`. That should be a satisfactory coefficient by itself. You should also be able to write
```python
>>> elapsedTime = Variable(0.)
>>> phi = CellVariable(mesh=..., value=...)
>>> eq = TransientTerm(coeff=elapsedTime * phi) == ...
```
If that sort of thing isn't working for you, please post a concrete example and we'll help get you going.

**Comment by oliverstefanov** [comment]
Thank you very much for this detailed answer. So using a Variable forces lazy evaluation of the expression.

Shouldn't the coefficient of the diffusion term be a FaceVariable in principle ? And if it's a CellVariable, Fipy will automatically convert to a FaceVariable ?

So I was able to use elapsed time as a Variable in the TransientTerm coefficient but only if I write it as "elapsed_time.value". Using "elapsed_time" gives me a warning saying the coefficient was converted to a CONSTANT CellVariable, which is no good I assume. And in this case I'm not sure whether using a Variable changes anything compared to using a regular float

**Comment by guyer** [comment]
Yes, ideally the coefficient of a `DiffusionTerm` should be a `FaceVariable`. As a convenience, if you supply a `CellVariable`, FiPy will automatically interpolate to a `FaceVariable` holding the arithmetic mean. If you want a different interpolation, or if you have some more direct way to calculate the value at the face, you should do so.

I'll have to do some tests with `TransientTerm` coefficients.

**Comment by oliverstefanov** [comment]
Alright thanks. Actually, regarding the interpolation of a FaceVariable, I think I saw in the examples that the arithmetic mean is usually used for the phase equation, but a harmonic mean is employed for concentration/chemical potential equation. Not sure why. Is that how it should be done ? I've only used arithmetic interpolation so far, which might be wrong.

And what if there is also a heat equation, should it be arithmetic or harmonic interpolation ? Does that really make a difference ?

**Comment by guyer** [comment]
The choice of interpolation can make an enormous difference. Mass must be conserved and must not be allowed to go below zero. At an abrupt interface between a dilute solution of 1e-6 and a six-nines pure material, what is the concentration at the interface? 50%? Probably not. Solutions tend to work much better if the interfacial concentration skews toward the low side. I've found the harmonic mean to work well.

Phase, on the other hand, is not conserved and it's usually not a disaster if it dips below zero or above 1 (assuming those are the bounds for your phase field).

Heat is conserved, but temperature is not. I'm not sure whether it matters how you interpolate temperature.

**Comment by oliverstefanov** [comment]
Ok great maybe that's partly why I encounter issues with my codes. I'll test with harmonic interpolation for the concentration field, as I sometimes get mass conservation problems (concentration goes below zero or above 1...)

**Comment by guyer** [comment]
Please reopen if you still have questions
