### ISSUE TITLE
setup.py install_requires, tests_require, extra_require do not reflect package requirements

### ISSUE THREAD

**Issue by costrouc** [usnistgov/fipy#660]
I along with @wd15 are packaging `fipy` for nixpkgs. One of the difficulties with packaging fipy is that the `setup.py` does not reflect the requirements of the package (from what I can tell). I think it would be worth filling in the extras_require and tests_require to fully reflect requirements.

**Comment by wd15** [comment]
I think that we kind of gave up on Pip in favor of Conda-forge. The recipe is here, https://github.com/conda-forge/fipy-feedstock/blob/master/recipe/meta.yaml for that. That along with Nix recipe should give a lot of clues. However, since Nixpkgs kind of relies on PyPi for the code base then we should make the setup.py work correctly and also upload the latest release of FiPy to PyPI. I'll try and address this issues over the next few weeks.
 
The problem for us is that two of FiPy's most important dependencies aren't supported in Python3 (and never will be). We can still use FiPy in Python 3, but it has very different dependencies from Python 2.

**Comment by costrouc** [comment]
Sounds great! Looks like this issue is resolved then
