### ISSUE TITLE
Unable to evaluate logarithm of cellvariables

### ISSUE THREAD

**Issue by pavaninguva** [usnistgov/fipy#685]
Hi, I am trying to evaluate a logarithim of a cellvariable to modify the partial derivative $\frac{\partial f}{\partial phi}$ in this example: https://www.ctcms.nist.gov/fipy/examples/cahnHilliard/generated/examples.cahnHilliard.mesh2D.html

However, it seems that I am unable to evaluate a logarithm of a cellvariable. The error can be reproduced as follows in this MWE: 

```
from fipy import CellVariable, Grid2D
from math import log

mesh = Grid2D(nx=10, ny=10, dx=0.25, dy=0.25)
phi = CellVariable(name=r"$\phi$", mesh=mesh)

dfdphi = phi * (1 - phi) * (1 - 2 * phi) + log(phi)
```
Where upon running, I get the following error: 
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    dfdphi = phi * (1 - phi) * (1 - 2 * phi) + log(phi)
  File "/home/pavaninguva/miniconda3/envs/fipy/lib/python2.7/site-packages/fipy/variables/variable.py", line 1339, in __float__
    return float(self.value)
TypeError: only size-1 arrays can be converted to Python scalars
```
Thanks for your help!

**Comment by wd15** [comment]
I don't think `math.log` knows how to operate on anything but objects of size 1. That would be ints, floats or Numpy arrays of size 1. It doesn't work with larger Numpy arrays so certainly won't work with FiPy's CellVariable objects. Regardless, when operating on CellVariables it is best to use FiPy's numerix library. For example,

    >>> from fipy imprt numerix
    >>> a = numerix.log(phi)
    >>> type(a)
    fipy.variables.unaryOperatorVariable._UnaryOperatorVariable.<locals>.unOp

By using `numerix.log` the resulting object has the same variable properties. Also, if `phi` changes value then so does `a` since `a` knows that it depends on `phi`.

    >>> print(repr(a))
    log($\phi$)

**Comment by pavaninguva** [comment]
Awesome! That worked perfectly! Thank you so much!!!
