### ISSUE TITLE
viewer() won't plot two datasets with different mesh sizes in one graph

### ISSUE THREAD

**Issue by matthijsnuus** [usnistgov/fipy#724]
I've been trying to plot 2 variables in one plot, but it only seems to work if both of these have the same sized mesh. Could someone try to figure out how I can plot these two different lines with different meshes in the same figure rather than being plotted seperately? 

my code:
https://pastebin.com/raw/JV6JDfXe

It seems to automatically plot them in the same graph if I change my mesh2 to the regular mesh and e.g. give the remaining values the value 0.

**Comment by wd15** [comment]
It's probably (not, see below) best to interpolate the variables to the same mesh. FiPy has some built in interpolation using the `__call__` method in `CellVariables`s. For example, the following has two variables on different meshes `mesh0` and `mesh1`, but creates a new variable on `mesh0` so both variables are on the same mesh. 

```
from fipy import Grid1D, CellVariable, Viewer

nx = 100
dx = 1 / nx

mesh0 = Grid1D(nx=nx, dx=dx)
mesh1 = Grid1D(nx=nx // 2, dx=dx * 2)

var0 = CellVariable(mesh=mesh0, value=mesh0.x)
var1 = CellVariable(mesh=mesh1, value=mesh1.x**2)
var1_on_mesh0 = CellVariable(mesh0)
var1_on_mesh0[:] = var1((mesh0.x,), order=1)

viewer = Viewer((var0, var1_on_mesh0))

viewer.plot()

input('wait')
```

FiPy's built in interpolation is probably not as good as Scipy's now. Try Scipy's [interp1D](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html) if you want something better.

Alternatively you can just use raw Matplotlib code instead of FiPy's viewer. This is actually easier than the above solution.

```
from fipy import Grid1D, CellVariable, Viewer
import matplotlib.pyplot as plt

nx = 100
dx = 1 / nx

mesh0 = Grid1D(nx=nx, dx=dx)
mesh1 = Grid1D(nx=nx // 2, dx=dx * 2)

var0 = CellVariable(mesh=mesh0, value=mesh0.x)
var1 = CellVariable(mesh=mesh1, value=mesh1.x**2)

plt.plot((mesh0.x, mesh1.x), (var0, var1))


input('wait')

```

**Comment by matthijsnuus** [comment]
Thanks a lot! I managed to figure it out using the same mesh method and just leaving the remaining data empty. But the interpolation method will come in use for some later adjustments.
